---
title: "Visualization_1"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r, echo=FALSE}
suppressPackageStartupMessages(library(dplyr))
suppressPackageStartupMessages(library(googleVis))
```
```{r, cache=TRUE, echo=FALSE}
train_data <- read.csv("bigquery-geotab-intersection-congestion/train.csv", stringsAsFactors = FALSE)
```
```{r, cache=TRUE, echo=FALSE}
atlanta <- filter(train_data, City == "Atlanta")
atlanta$EntryHeading <- ifelse(atlanta$EntryHeading == "N", 90,
                               ifelse(atlanta$EntryHeading == "W", 180,
                                      ifelse(atlanta$EntryHeading == "E", 0,
                                             ifelse(atlanta$EntryHeading == "S", 270,
                                                    ifelse(atlanta$EntryHeading == "NE", 45,
                                                           ifelse(atlanta$EntryHeading == "NW", 135,
                                                                  ifelse(atlanta$EntryHeading == "SW", 225,
                                                                         ifelse(atlanta$EntryHeading == "SE", 315, "something wrong"))))))))

atlanta$ExitHeading <- ifelse(atlanta$ExitHeading == "N", 90,
                               ifelse(atlanta$ExitHeading == "W", 180,
                                      ifelse(atlanta$ExitHeading == "E", 0,
                                             ifelse(atlanta$ExitHeading == "S", 270,
                                                    ifelse(atlanta$ExitHeading == "NE", 45,
                                                           ifelse(atlanta$ExitHeading == "NW", 135,
                                                                  ifelse(atlanta$ExitHeading == "SW", 225,
                                                                         ifelse(atlanta$ExitHeading == "SE", 315, "something wrong"))))))))

atlanta$EntryHeading <- as.integer(atlanta$EntryHeading)
atlanta$ExitHeading <- as.integer(atlanta$ExitHeading)

atlanta$TurnType <- ifelse(atlanta$ExitHeading == atlanta$EntryHeading | atlanta$EntryStreetName == atlanta$ExitStreetName, "straight",
                           ifelse(atlanta$ExitHeading - atlanta$EntryHeading > 0 & atlanta$ExitHeading - atlanta$EntryHeading < 180, "left",
                                  ifelse(atlanta$ExitHeading - atlanta$EntryHeading < 0 | atlanta$ExitHeading - atlanta$EntryHeading > 180, "right",
                                         ifelse(atlanta$ExitHeading - atlanta$EntryHeading == 180, "u-turn", "something went wrong"))))

atlanta_weekday <- filter(atlanta, City == "Atlanta", Weekend == 0, Month == 6)
atlanta_weekday$Path.Int <- paste(atlanta_weekday$Path, as.character(atlanta_weekday$IntersectionId), sep = "_")
m <- gvisMotionChart(atlanta_weekday, idvar = "Path.Int", timevar = "Hour", xvar = "Latitude", yvar = "Longitude", sizevar = "TotalTimeStopped_p50", colorvar = "TurnType", date.format = "%H", options = list(height = 1000, width = 1400))

```
```{r,  results='asis', tidy=FALSE, echo=FALSE}
x <- table(atlanta_weekday$TurnType)
pie <- gvisPieChart(data.frame(x))

```
```{r gv,results="asis"}
suppressPackageStartupMessages(library(googleVis))
M <- gvisMotionChart(Fruits, "Fruit", "Year",
                     options=list(width=600, height=400))
print(M,"chart")
```
Here is some stat about traffic data in Atlanta

